/**
 * The generation pipeline: turn a {@link ServerSpec} into an in-memory set of
 * files ({@link GeneratedFile}[]) for a production-shaped MCP server.
 *
 * This module is pure (no filesystem side effects) so it can be unit-tested by
 * inspecting the generated strings; {@link scaffold} in scaffold.ts writes the
 * result to disk. The generated project depends only on Node built-ins and
 * implements the MCP 2025-06-18 JSON-RPC methods over the stdio transport:
 *
 *   initialize, notifications/initialized, ping,
 *   tools/list, tools/call,
 *   resources/list, resources/read, resources/templates/list,
 *   prompts/list, prompts/get
 *
 * Every generated `.mjs` uses Node built-ins only, `\n`-delimited JSON-RPC
 * framing (no embedded newlines), and writes only valid MCP messages to stdout
 * (logs go to stderr). Original Cognis Digital implementation.
 */

import { MCP_PROTOCOL_VERSION } from "./types.js";
import type {
  PromptDefinition,
  ResourceDefinition,
  ResourceTemplateDefinition,
  ServerSpec,
  ToolDefinition,
} from "./types.js";

/** A single generated file: repo-relative POSIX path + UTF-8 contents. */
export interface GeneratedFile {
  path: string;
  contents: string;
}

/** Convert a primitive name to a safe JS identifier for handler wiring. */
function ident(name: string): string {
  const id = name.replace(/[^A-Za-z0-9_$]/g, "_");
  return /^[A-Za-z_$]/.test(id) ? id : `_${id}`;
}

/** Convert a URI/template to a safe filename fragment. */
function slug(s: string): string {
  return s.replace(/[^A-Za-z0-9._-]+/g, "_").replace(/^_+|_+$/g, "") || "item";
}

/**
 * Build a minimal, schema-valid arguments object for a tool's required inputs.
 * Integers/numbers get `1`, booleans get `true`, everything else gets
 * `stringSample`. Shared by the generated test and smoke-script emitters so both
 * exercise the tool with the same (valid) call shape.
 */
function sampleArgsForTool(
  tool: ToolDefinition | undefined,
  stringSample: string
): Record<string, unknown> {
  const args: Record<string, unknown> = {};
  const props = tool?.inputSchema?.properties ?? {};
  for (const req of tool?.inputSchema?.required ?? []) {
    const p = props[req];
    const t = Array.isArray(p?.type) ? p?.type[0] : p?.type;
    args[req] =
      t === "integer" || t === "number" ? 1 : t === "boolean" ? true : stringSample;
  }
  return args;
}

const HEADER = "// Generated by mcpscaffold. Original Cognis Digital implementation.\n";

/** Emit `export default <json>` so handlers/specs can be imported directly. */
function jsonModule(value: unknown, exportName = "default"): string {
  const kw = exportName === "default" ? "export default" : `export const ${exportName} =`;
  return `${HEADER}${kw} ${JSON.stringify(value, null, 2)};\n`;
}

/* ------------------------------------------------------------------ *
 * Handler stubs                                                       *
 * ------------------------------------------------------------------ */

function toolHandlerFile(tool: ToolDefinition): GeneratedFile {
  const id = ident(tool.name);
  const isEcho = tool.name === "echo";
  const body = isEcho
    ? `  // Sample implementation. Replace with your own logic.\n` +
      `  const text = String(args.text ?? "");\n` +
      `  return {\n` +
      `    content: [{ type: "text", text }],\n` +
      `    structuredContent: { text },\n` +
      `  };`
    : `  // TODO: implement "${tool.name}". Return MCP tool-call content.\n` +
      `  //\n` +
      `  // Return shape (MCP 2025-06-18 tools/call result):\n` +
      `  //   { content: [{ type: "text", text: string }], structuredContent?: object, isError?: boolean }\n` +
      `  const summary = ${JSON.stringify(`${tool.name} called`)} + " with " + JSON.stringify(args);\n` +
      `  return { content: [{ type: "text", text: summary }] };`;
  return {
    path: `src/tools/${slug(tool.name)}.mjs`,
    contents:
      HEADER +
      `// Tool handler: ${tool.name} — ${tool.description}\n` +
      `//\n` +
      `// @param {Record<string, unknown>} args  Arguments (already schema-validated by the registry).\n` +
      `// @returns MCP tools/call result: { content, structuredContent?, isError? }\n` +
      `export function ${id}(args) {\n${body}\n}\n`,
  };
}

function resourceHandlerFile(res: ResourceDefinition): GeneratedFile {
  const id = ident(res.name);
  const mime = res.mimeType ?? "text/plain";
  return {
    path: `src/resources/${slug(res.name)}.mjs`,
    contents:
      HEADER +
      `// Resource handler: ${res.name} (${res.uri})\n` +
      `//\n` +
      `// @param {string} uri  The resource URI being read.\n` +
      `// @returns MCP resources/read contents entry: { uri, mimeType?, text? | blob? }\n` +
      `export function ${id}(uri) {\n` +
      `  // TODO: return the real contents for "${res.uri}".\n` +
      `  return {\n` +
      `    uri,\n` +
      `    mimeType: ${JSON.stringify(mime)},\n` +
      `    text: ${JSON.stringify(`Contents of ${res.name}. Replace this in src/resources/${slug(res.name)}.mjs.`)},\n` +
      `  };\n` +
      `}\n`,
  };
}

function resourceTemplateHandlerFile(
  tmpl: ResourceTemplateDefinition
): GeneratedFile {
  const id = ident(tmpl.name);
  const mime = tmpl.mimeType ?? "text/plain";
  return {
    path: `src/resource_templates/${slug(tmpl.name)}.mjs`,
    contents:
      HEADER +
      `// Resource-template handler: ${tmpl.name} (${tmpl.uriTemplate})\n` +
      `//\n` +
      `// Matches a concrete URI produced from the template and returns its contents.\n` +
      `// @param {string} uri   The concrete URI being read.\n` +
      `// @param {Record<string,string>} vars  Variables extracted from the template.\n` +
      `// @returns MCP resources/read contents entry: { uri, mimeType?, text? | blob? }\n` +
      `export const uriTemplate = ${JSON.stringify(tmpl.uriTemplate)};\n\n` +
      `export function ${id}(uri, vars) {\n` +
      `  // TODO: build the real contents from the template variables.\n` +
      `  return {\n` +
      `    uri,\n` +
      `    mimeType: ${JSON.stringify(mime)},\n` +
      `    text: ${JSON.stringify("Rendered from template. vars=")} + JSON.stringify(vars ?? {}),\n` +
      `  };\n` +
      `}\n`,
  };
}

function promptHandlerFile(prompt: PromptDefinition): GeneratedFile {
  const id = ident(prompt.name);
  return {
    path: `src/prompts/${slug(prompt.name)}.mjs`,
    contents:
      HEADER +
      `// Prompt handler: ${prompt.name}${prompt.description ? " — " + prompt.description : ""}\n` +
      `//\n` +
      `// @param {Record<string, unknown>} args  Prompt arguments (required ones checked by the registry).\n` +
      `// @returns MCP prompts/get result: { description?, messages: [{ role, content: { type:"text", text } }] }\n` +
      `export function ${id}(args) {\n` +
      `  // TODO: build your prompt messages from args.\n` +
      `  const text = ${JSON.stringify(`Prompt "${prompt.name}". Arguments: `)} + JSON.stringify(args ?? {});\n` +
      `  return {\n` +
      `    description: ${JSON.stringify(prompt.description ?? prompt.name)},\n` +
      `    messages: [{ role: "user", content: { type: "text", text } }],\n` +
      `  };\n` +
      `}\n`,
  };
}

/* ------------------------------------------------------------------ *
 * Auth stub                                                           *
 * ------------------------------------------------------------------ */

function authFile(spec: ServerSpec): GeneratedFile {
  const scheme = spec.auth?.scheme ?? "none";
  const envVar = spec.auth?.tokenEnvVar ?? "MCP_BEARER_TOKEN";
  const note = spec.auth?.note ?? "Authorization hook.";
  const bearerExample =
    `//\n` +
    `// Example: enforce a bearer token from the environment. Uncomment and adapt.\n` +
    `// Note: the stdio transport has no HTTP headers; a real bearer check belongs\n` +
    `// in an HTTP transport. This example reads a shared secret from the\n` +
    `// environment as a stand-in so the hook shape is clear.\n` +
    `//\n` +
    `// export function authorize(request) {\n` +
    `//   const expected = process.env[${JSON.stringify(envVar)}];\n` +
    `//   if (!expected) return { ok: true }; // not configured -> allow\n` +
    `//   const presented = process.env.MCP_PRESENTED_TOKEN; // wire from your transport\n` +
    `//   if (presented === expected) return { ok: true };\n` +
    `//   return { ok: false, code: -32001, message: "unauthorized" };\n` +
    `// }\n`;
  return {
    path: "src/auth.mjs",
    contents:
      HEADER +
      `// Authorization hook — ${note}\n` +
      `//\n` +
      `// DEFENSIVE DEFAULT: this allows every request (a place to plug in auth),\n` +
      `// and returns a TODO marker so it is easy to find. Replace with a real\n` +
      `// authorization decision. It is called for every JSON-RPC request in\n` +
      `// server.mjs; return { ok: false, code, message } to reject.\n` +
      `//\n` +
      `// Scheme selected in the ServerSpec: ${JSON.stringify(scheme)}\n` +
      (scheme === "bearer" ? bearerExample : "") +
      `\n` +
      `export function authorize(request) {\n` +
      `  // TODO: implement real authorization. Default: allow.\n` +
      `  void request;\n` +
      `  return { ok: true };\n` +
      `}\n`,
  };
}

/* ------------------------------------------------------------------ *
 * Transport (stdio)                                                   *
 * ------------------------------------------------------------------ */

function transportFile(): GeneratedFile {
  return {
    path: "src/transport.mjs",
    contents:
      HEADER +
      `// stdio transport for MCP (spec 2025-06-18).\n` +
      `//\n` +
      `// Framing: JSON-RPC messages are UTF-8, newline-delimited, and MUST NOT\n` +
      `// contain embedded newlines (JSON.stringify never emits raw newlines, so\n` +
      `// each message is exactly one line). Only valid MCP messages go to stdout;\n` +
      `// diagnostics go to stderr.\n` +
      `\n` +
      `import { createInterface } from "node:readline";\n` +
      `\n` +
      `// Serialize one JSON-RPC message to a single stdout line.\n` +
      `export function writeMessage(message) {\n` +
      `  process.stdout.write(JSON.stringify(message) + "\\n");\n` +
      `}\n` +
      `\n` +
      `// Read newline-delimited JSON-RPC messages from stdin, invoking onMessage\n` +
      `// for each parsed object. Blank lines are ignored. Returns a promise that\n` +
      `// resolves when stdin closes.\n` +
      `export function readMessages(onMessage, input = process.stdin) {\n` +
      `  const rl = createInterface({ input, crlfDelay: Infinity });\n` +
      `  rl.on("line", (line) => {\n` +
      `    const trimmed = line.trim();\n` +
      `    if (trimmed.length === 0) return;\n` +
      `    let parsed;\n` +
      `    try {\n` +
      `      parsed = JSON.parse(trimmed);\n` +
      `    } catch (err) {\n` +
      `      // Parse error: reply per JSON-RPC (-32700) with a null id.\n` +
      `      writeMessage({ jsonrpc: "2.0", id: null, error: { code: -32700, message: "parse error" } });\n` +
      `      return;\n` +
      `    }\n` +
      `    Promise.resolve(onMessage(parsed)).catch((err) => {\n` +
      `      process.stderr.write("handler error: " + (err && err.stack || err) + "\\n");\n` +
      `    });\n` +
      `  });\n` +
      `  return new Promise((resolve) => rl.on("close", resolve));\n` +
      `}\n`,
  };
}

/* ------------------------------------------------------------------ *
 * Server (JSON-RPC method router)                                     *
 * ------------------------------------------------------------------ */

function serverFile(spec: ServerSpec): GeneratedFile {
  const tools = spec.tools ?? [];
  const resources = spec.resources ?? [];
  const templates = spec.resourceTemplates ?? [];
  const prompts = spec.prompts ?? [];

  const toolImports = tools
    .map((t) => `import { ${ident(t.name)} } from "./tools/${slug(t.name)}.mjs";`)
    .join("\n");
  const resourceImports = resources
    .map((r) => `import { ${ident(r.name)} } from "./resources/${slug(r.name)}.mjs";`)
    .join("\n");
  const templateImports = templates
    .map(
      (t) =>
        `import { ${ident(t.name)} as tmpl_${ident(t.name)}, uriTemplate as tmplUri_${ident(t.name)} } from "./resource_templates/${slug(t.name)}.mjs";`
    )
    .join("\n");
  const promptImports = prompts
    .map((p) => `import { ${ident(p.name)} } from "./prompts/${slug(p.name)}.mjs";`)
    .join("\n");

  const toolHandlerMap = tools.map((t) => `  ${JSON.stringify(t.name)}: ${ident(t.name)},`).join("\n");
  const resourceHandlerMap = resources
    .map((r) => `  ${JSON.stringify(r.uri)}: ${ident(r.name)},`)
    .join("\n");
  const promptHandlerMap = prompts
    .map((p) => `  ${JSON.stringify(p.name)}: ${ident(p.name)},`)
    .join("\n");
  const templateEntries = templates
    .map(
      (t) =>
        `  { uriTemplate: tmplUri_${ident(t.name)}, handler: tmpl_${ident(t.name)} },`
    )
    .join("\n");

  const capabilities: Record<string, unknown> = {};
  if (tools.length > 0) capabilities.tools = { listChanged: false };
  if (resources.length > 0 || templates.length > 0)
    capabilities.resources = { subscribe: false, listChanged: false };
  if (prompts.length > 0) capabilities.prompts = { listChanged: false };

  const serverInfo: Record<string, string> = { name: spec.name, version: spec.version };
  if (spec.title) serverInfo.title = spec.title;

  return {
    path: "src/server.mjs",
    contents:
      `#!/usr/bin/env node\n` +
      HEADER +
      `// MCP server "${spec.name}" — JSON-RPC 2.0 router over the stdio transport.\n` +
      `// Targets MCP specification version ${MCP_PROTOCOL_VERSION}.\n` +
      `\n` +
      `import { readMessages, writeMessage } from "./transport.mjs";\n` +
      `import { authorize } from "./auth.mjs";\n` +
      (toolImports ? toolImports + "\n" : "") +
      (resourceImports ? resourceImports + "\n" : "") +
      (templateImports ? templateImports + "\n" : "") +
      (promptImports ? promptImports + "\n" : "") +
      `\n` +
      `export const PROTOCOL_VERSION = ${JSON.stringify(MCP_PROTOCOL_VERSION)};\n` +
      `\n` +
      `// Static primitive catalogs (advertised via */list).\n` +
      `export const TOOLS = ${JSON.stringify(tools, null, 2)};\n` +
      `export const RESOURCES = ${JSON.stringify(resources, null, 2)};\n` +
      `export const RESOURCE_TEMPLATES = ${JSON.stringify(templates, null, 2)};\n` +
      `export const PROMPTS = ${JSON.stringify(prompts, null, 2)};\n` +
      `\n` +
      `const toolHandlers = {\n${toolHandlerMap}\n};\n` +
      `const resourceHandlers = {\n${resourceHandlerMap}\n};\n` +
      `const promptHandlers = {\n${promptHandlerMap}\n};\n` +
      `const templateHandlers = [\n${templateEntries}\n];\n` +
      `\n` +
      `const SERVER_INFO = ${JSON.stringify(serverInfo, null, 2)};\n` +
      `const CAPABILITIES = ${JSON.stringify(capabilities, null, 2)};\n` +
      (spec.instructions
        ? `const INSTRUCTIONS = ${JSON.stringify(spec.instructions)};\n`
        : `const INSTRUCTIONS = undefined;\n`) +
      `\n` +
      SERVER_ROUTER_BODY,
  };
}

/**
 * The transport-agnostic method router shared by every generated server. It is
 * a constant string (does not depend on the spec) so the per-server file above
 * only has to supply the catalogs, handler maps, and identity constants.
 */
const SERVER_ROUTER_BODY = `// --- JSON-RPC helpers -------------------------------------------------------

function result(id, value) {
  return { jsonrpc: "2.0", id, result: value };
}
function error(id, code, message, data) {
  const err = { code, message };
  if (data !== undefined) err.data = data;
  return { jsonrpc: "2.0", id, error: err };
}

// Minimal RFC 6570 level-1 matcher: does \`uri\` match \`template\`, and if so
// what are the {var} bindings? Only simple {name} expansions are supported.
function matchTemplate(template, uri) {
  const names = [];
  const pattern = template.replace(/[.*+?^\${}()|[\\]\\\\]/g, (ch) =>
    ch === "{" || ch === "}" ? ch : "\\\\" + ch
  );
  const regexSrc =
    "^" +
    pattern.replace(/\\{([^}]+)\\}/g, (_m, name) => {
      names.push(name);
      return "([^/]+)";
    }) +
    "$";
  const m = new RegExp(regexSrc).exec(uri);
  if (!m) return null;
  const vars = {};
  names.forEach((n, i) => (vars[n] = decodeURIComponent(m[i + 1])));
  return vars;
}

// --- Method handlers --------------------------------------------------------

export async function handleRequest(msg) {
  const { id, method, params } = msg;

  const decision = authorize(msg);
  if (decision && decision.ok === false) {
    return error(id, decision.code ?? -32001, decision.message ?? "unauthorized");
  }

  switch (method) {
    case "initialize": {
      const requested = params && params.protocolVersion;
      // Echo the client's version if we support it; otherwise offer ours.
      const protocolVersion =
        requested === PROTOCOL_VERSION ? requested : PROTOCOL_VERSION;
      const res = { protocolVersion, capabilities: CAPABILITIES, serverInfo: SERVER_INFO };
      if (INSTRUCTIONS !== undefined) res.instructions = INSTRUCTIONS;
      return result(id, res);
    }
    case "ping":
      return result(id, {});
    case "tools/list":
      return result(id, { tools: TOOLS });
    case "tools/call": {
      const name = params && params.name;
      const handler = toolHandlers[name];
      if (!handler) return error(id, -32602, "unknown tool: " + name);
      try {
        const out = await handler((params && params.arguments) || {});
        // Handlers may return a full tools/call result or a bare value.
        if (out && Array.isArray(out.content)) return result(id, out);
        return result(id, { content: [{ type: "text", text: JSON.stringify(out) }] });
      } catch (err) {
        return result(id, {
          content: [{ type: "text", text: String((err && err.message) || err) }],
          isError: true,
        });
      }
    }
    case "resources/list":
      return result(id, { resources: RESOURCES });
    case "resources/templates/list":
      return result(id, {
        resourceTemplates: RESOURCE_TEMPLATES,
      });
    case "resources/read": {
      const uri = params && params.uri;
      const handler = resourceHandlers[uri];
      if (handler) {
        const contents = await handler(uri);
        return result(id, { contents: [contents] });
      }
      for (const t of templateHandlers) {
        const vars = matchTemplate(t.uriTemplate, uri);
        if (vars) {
          const contents = await t.handler(uri, vars);
          return result(id, { contents: [contents] });
        }
      }
      return error(id, -32002, "resource not found", { uri });
    }
    case "prompts/list":
      return result(id, { prompts: PROMPTS });
    case "prompts/get": {
      const name = params && params.name;
      const handler = promptHandlers[name];
      if (!handler) return error(id, -32602, "unknown prompt: " + name);
      const got = await handler((params && params.arguments) || {});
      return result(id, got);
    }
    default:
      return error(id, -32601, "method not found: " + method);
  }
}

// --- Entry point ------------------------------------------------------------

export async function handleMessage(msg) {
  // Notifications (no id) get no response. We only care about "initialized".
  if (msg && msg.id === undefined) {
    return; // e.g. notifications/initialized
  }
  const response = await handleRequest(msg);
  if (response) writeMessage(response);
}

async function main() {
  process.stderr.write(
    "[" + SERVER_INFO.name + " " + SERVER_INFO.version + "] MCP server ready on stdio (" +
      TOOLS.length + " tools, " + RESOURCES.length + " resources, " +
      RESOURCE_TEMPLATES.length + " templates, " + PROMPTS.length + " prompts)\\n"
  );
  await readMessages(handleMessage);
}

// Run only when executed directly (not when imported by tests).
const invokedDirectly =
  process.argv[1] && process.argv[1].replace(/\\\\/g, "/").endsWith("src/server.mjs");
if (invokedDirectly) {
  main().catch((err) => {
    process.stderr.write(String((err && err.stack) || err) + "\\n");
    process.exit(1);
  });
}
`;

/* ------------------------------------------------------------------ *
 * Project scaffolding files (package.json, tests, docs, spec.json)    *
 * ------------------------------------------------------------------ */

function packageJsonFile(spec: ServerSpec): GeneratedFile {
  const pkg = {
    name: spec.name,
    version: spec.version,
    description: `MCP server: ${spec.name}`,
    type: "module",
    private: true,
    bin: { [spec.name]: "src/server.mjs" },
    scripts: {
      start: "node src/server.mjs",
      test: 'node --test "test/*.test.mjs"',
    },
    engines: { node: ">=18" },
    author: "Cognis Digital",
  };
  return { path: "package.json", contents: JSON.stringify(pkg, null, 2) + "\n" };
}

function serverTestFile(spec: ServerSpec): GeneratedFile {
  const firstTool = (spec.tools ?? [])[0];
  const toolName = firstTool?.name;
  // Build a minimal valid arguments object for the first tool from its schema.
  const args = sampleArgsForTool(firstTool, "sample");

  const toolCallTest = toolName
    ? `
test("tools/call invokes ${toolName} and returns MCP content", async () => {
  const res = await handleRequest({
    jsonrpc: "2.0",
    id: 3,
    method: "tools/call",
    params: { name: ${JSON.stringify(toolName)}, arguments: ${JSON.stringify(args)} },
  });
  assert.equal(res.jsonrpc, "2.0");
  assert.ok(res.result, "expected a result");
  assert.ok(Array.isArray(res.result.content), "expected content array");
  assert.equal(res.result.content[0].type, "text");
});
`
    : "";

  const resourceTest = (spec.resources ?? [])[0]
    ? `
test("resources/read returns contents for a known uri", async () => {
  const res = await handleRequest({
    jsonrpc: "2.0",
    id: 4,
    method: "resources/read",
    params: { uri: ${JSON.stringify((spec.resources ?? [])[0].uri)} },
  });
  assert.ok(Array.isArray(res.result.contents));
  assert.ok(res.result.contents[0].text !== undefined || res.result.contents[0].blob !== undefined);
});
`
    : "";

  const promptTest = (spec.prompts ?? [])[0]
    ? `
test("prompts/get renders messages", async () => {
  const p = ${JSON.stringify((spec.prompts ?? [])[0].name)};
  const required = ${JSON.stringify(
    Object.fromEntries(
      ((spec.prompts ?? [])[0].arguments ?? [])
        .filter((a) => a.required)
        .map((a) => [a.name, "sample"])
    )
  )};
  const res = await handleRequest({
    jsonrpc: "2.0",
    id: 5,
    method: "prompts/get",
    params: { name: p, arguments: required },
  });
  assert.ok(Array.isArray(res.result.messages));
  assert.ok(res.result.messages.length >= 1);
});
`
    : "";

  return {
    path: "test/server.test.mjs",
    contents:
      HEADER +
      `import { test } from "node:test";\n` +
      `import assert from "node:assert/strict";\n` +
      `import { handleRequest, PROTOCOL_VERSION } from "../src/server.mjs";\n` +
      `\n` +
      `test("initialize returns protocolVersion, capabilities, serverInfo", async () => {\n` +
      `  const res = await handleRequest({\n` +
      `    jsonrpc: "2.0", id: 1, method: "initialize",\n` +
      `    params: { protocolVersion: PROTOCOL_VERSION, capabilities: {}, clientInfo: { name: "test", version: "0" } },\n` +
      `  });\n` +
      `  assert.equal(res.result.protocolVersion, PROTOCOL_VERSION);\n` +
      `  assert.ok(res.result.capabilities);\n` +
      `  assert.equal(res.result.serverInfo.name, ${JSON.stringify(spec.name)});\n` +
      `});\n` +
      `\n` +
      `test("tools/list advertises the tool catalog", async () => {\n` +
      `  const res = await handleRequest({ jsonrpc: "2.0", id: 2, method: "tools/list" });\n` +
      `  assert.ok(Array.isArray(res.result.tools));\n` +
      `  assert.equal(res.result.tools.length, ${(spec.tools ?? []).length});\n` +
      `});\n` +
      toolCallTest +
      resourceTest +
      promptTest +
      `\ntest("unknown method returns -32601", async () => {\n` +
      `  const res = await handleRequest({ jsonrpc: "2.0", id: 9, method: "no/such" });\n` +
      `  assert.equal(res.error.code, -32601);\n` +
      `});\n`,
  };
}

function smokeScriptFile(spec: ServerSpec): GeneratedFile {
  const firstTool = (spec.tools ?? [])[0];
  const args = sampleArgsForTool(firstTool, "hello");
  return {
    path: "scripts/smoke.mjs",
    contents:
      HEADER +
      `// End-to-end smoke test: spawn the server, send initialize + tools/call\n` +
      `// over stdio, and assert on valid MCP responses. Exits 0 on success.\n` +
      `import { spawn } from "node:child_process";\n` +
      `import { fileURLToPath } from "node:url";\n` +
      `import { dirname, join } from "node:path";\n` +
      `\n` +
      `const here = dirname(fileURLToPath(import.meta.url));\n` +
      `const serverPath = join(here, "..", "src", "server.mjs");\n` +
      `\n` +
      `const child = spawn(process.execPath, [serverPath], { stdio: ["pipe", "pipe", "inherit"] });\n` +
      `let buffer = "";\n` +
      `const pending = new Map();\n` +
      `child.stdout.on("data", (chunk) => {\n` +
      `  buffer += chunk.toString("utf8");\n` +
      `  let nl;\n` +
      `  while ((nl = buffer.indexOf("\\n")) >= 0) {\n` +
      `    const line = buffer.slice(0, nl).trim();\n` +
      `    buffer = buffer.slice(nl + 1);\n` +
      `    if (!line) continue;\n` +
      `    const msg = JSON.parse(line);\n` +
      `    const resolve = pending.get(msg.id);\n` +
      `    if (resolve) { pending.delete(msg.id); resolve(msg); }\n` +
      `  }\n` +
      `});\n` +
      `function send(msg) {\n` +
      `  return new Promise((resolve) => {\n` +
      `    pending.set(msg.id, resolve);\n` +
      `    child.stdin.write(JSON.stringify(msg) + "\\n");\n` +
      `  });\n` +
      `}\n` +
      `function fail(m) { console.error("SMOKE FAIL: " + m); child.kill(); process.exit(1); }\n` +
      `\n` +
      `const init = await send({ jsonrpc: "2.0", id: 1, method: "initialize", params: { protocolVersion: "${MCP_PROTOCOL_VERSION}", capabilities: {}, clientInfo: { name: "smoke", version: "0" } } });\n` +
      `if (!init.result || !init.result.serverInfo) fail("initialize did not return serverInfo");\n` +
      `console.error("initialize ok: " + init.result.serverInfo.name + " " + init.result.serverInfo.version);\n` +
      `\n` +
      `const listed = await send({ jsonrpc: "2.0", id: 2, method: "tools/list" });\n` +
      `if (!Array.isArray(listed.result.tools)) fail("tools/list did not return an array");\n` +
      `console.error("tools/list ok: " + listed.result.tools.length + " tool(s)");\n` +
      (firstTool
        ? `const called = await send({ jsonrpc: "2.0", id: 3, method: "tools/call", params: { name: ${JSON.stringify(
            firstTool.name
          )}, arguments: ${JSON.stringify(args)} } });\n` +
          `if (!called.result || !Array.isArray(called.result.content)) fail("tools/call did not return content");\n` +
          `console.error("tools/call ok: " + JSON.stringify(called.result.content[0]));\n`
        : "") +
      `\n` +
      `child.stdin.end();\n` +
      `child.kill();\n` +
      `console.error("SMOKE OK");\n` +
      `process.exit(0);\n`,
  };
}

function readmeFile(spec: ServerSpec): GeneratedFile {
  const toolLines = (spec.tools ?? []).map((t) => `- \`${t.name}\` — ${t.description}`).join("\n");
  const resLines = (spec.resources ?? []).map((r) => `- \`${r.uri}\` (${r.name})`).join("\n");
  const promptLines = (spec.prompts ?? []).map((p) => `- \`${p.name}\``).join("\n");
  return {
    path: "README.md",
    contents:
      `# ${spec.name}\n\n` +
      `A Model Context Protocol (MCP) server scaffolded with ` +
      `[mcpscaffold](https://github.com/cognis-digital/mcpscaffold), ` +
      `targeting MCP spec version \`${MCP_PROTOCOL_VERSION}\`.\n\n` +
      `## Run\n\n\`\`\`sh\nnpm start        # start the server on stdio\nnpm test         # run the generated test suite\nnode scripts/smoke.mjs   # end-to-end initialize + tools/call smoke test\n\`\`\`\n\n` +
      `## MCP methods implemented\n\n` +
      `\`initialize\`, \`ping\`, \`tools/list\`, \`tools/call\`, \`resources/list\`, ` +
      `\`resources/read\`, \`resources/templates/list\`, \`prompts/list\`, \`prompts/get\`.\n\n` +
      `## Primitives\n\n` +
      `### Tools\n${toolLines || "(none)"}\n\n` +
      `### Resources\n${resLines || "(none)"}\n\n` +
      `### Prompts\n${promptLines || "(none)"}\n\n` +
      `## Layout\n\n` +
      `- \`src/server.mjs\` — JSON-RPC router (the MCP methods above).\n` +
      `- \`src/transport.mjs\` — stdio, newline-delimited JSON-RPC framing.\n` +
      `- \`src/auth.mjs\` — authorization hook (default allow-with-TODO).\n` +
      `- \`src/tools/\`, \`src/resources/\`, \`src/resource_templates/\`, \`src/prompts/\` — one handler per primitive.\n` +
      `- \`test/server.test.mjs\` — node:test suite.\n` +
      `- \`spec.json\` — the ServerSpec this project was generated from.\n\n` +
      `## Add a primitive\n\n` +
      `Edit \`spec.json\`, re-run \`mcpscaffold new\` into a fresh dir (or add a handler\n` +
      `file and wire it in \`src/server.mjs\`). Validate with:\n\n` +
      `\`\`\`sh\nnpx @cognis-digital/mcpscaffold validate spec.json\n\`\`\`\n\n` +
      `License: COCL 1.0\n`,
  };
}

/* ------------------------------------------------------------------ *
 * Public entry point                                                  *
 * ------------------------------------------------------------------ */

/**
 * Generate the full file set for a server described by `spec`. Pure: returns
 * files in memory without touching the filesystem.
 */
export function generateServerFiles(spec: ServerSpec): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  files.push({ path: "spec.json", contents: JSON.stringify(spec, null, 2) + "\n" });
  files.push({
    path: "tools.json",
    contents: JSON.stringify(spec.tools ?? [], null, 2) + "\n",
  });

  files.push(transportFile());
  files.push(authFile(spec));
  files.push(serverFile(spec));

  for (const t of spec.tools ?? []) files.push(toolHandlerFile(t));
  for (const r of spec.resources ?? []) files.push(resourceHandlerFile(r));
  for (const t of spec.resourceTemplates ?? []) files.push(resourceTemplateHandlerFile(t));
  for (const p of spec.prompts ?? []) files.push(promptHandlerFile(p));

  files.push(packageJsonFile(spec));
  files.push(serverTestFile(spec));
  files.push(smokeScriptFile(spec));
  files.push(readmeFile(spec));
  files.push({ path: ".gitignore", contents: "node_modules/\n*.log\n" });

  return files;
}
