/**
 * ServerSpec helpers: a canonical example spec and a starter-spec generator.
 *
 * `EXAMPLE_SPEC` is a multi-primitive, auth-enabled spec used by the docs,
 * demos, and `init-spec`. `starterSpec(name)` produces a minimal-but-complete
 * spec (one tool + one resource + one prompt) used by `new` when no `--spec`
 * is supplied. Original Cognis Digital implementation.
 */

import type { ServerSpec } from "./types.js";

/** A minimal-but-complete starter spec: one tool, one resource, one prompt. */
export function starterSpec(name: string): ServerSpec {
  return {
    name,
    version: "0.1.0",
    title: name,
    instructions:
      `MCP server "${name}" scaffolded by mcpscaffold. ` +
      "Replace the sample tool/resource/prompt with your own.",
    tools: [
      {
        name: "echo",
        title: "Echo",
        description: "Echo back the provided text. A minimal sample tool.",
        inputSchema: {
          type: "object",
          properties: {
            text: { type: "string", description: "Text to echo back." },
          },
          required: ["text"],
        },
        outputSchema: {
          type: "object",
          properties: { text: { type: "string" } },
          required: ["text"],
        },
        annotations: { readOnlyHint: true, openWorldHint: false },
      },
    ],
    resources: [
      {
        uri: "info://readme",
        name: "readme",
        title: "Server README",
        description: "Human-readable notes about this server.",
        mimeType: "text/markdown",
      },
    ],
    resourceTemplates: [
      {
        uriTemplate: "greeting://{who}",
        name: "greeting",
        title: "Greeting",
        description: "A parameterized greeting resource.",
        mimeType: "text/plain",
      },
    ],
    prompts: [
      {
        name: "summarize",
        title: "Summarize text",
        description: "Ask the model to summarize the provided text.",
        arguments: [
          { name: "text", description: "The text to summarize.", required: true },
          { name: "style", description: "Optional summary style.", required: false },
        ],
      },
    ],
    auth: { scheme: "none", note: "Plug in your authorization here." },
  };
}

/**
 * A richer canonical example: multiple tools (incl. one with outputSchema and
 * annotations), resources, a resource template, prompts, and bearer auth.
 * Defensive/read-only sample tools only.
 */
export const EXAMPLE_SPEC: ServerSpec = {
  name: "example-mcp-server",
  version: "1.0.0",
  title: "Example MCP Server",
  instructions:
    "Example server generated by mcpscaffold demonstrating tools, resources, " +
    "resource templates, prompts, and a bearer-auth hook.",
  tools: [
    {
      name: "echo",
      title: "Echo",
      description: "Echo back the provided text.",
      inputSchema: {
        type: "object",
        properties: { text: { type: "string", description: "Text to echo back." } },
        required: ["text"],
      },
      annotations: { readOnlyHint: true },
    },
    {
      name: "add",
      title: "Add integers",
      description: "Add two integers and return the sum as structured content.",
      inputSchema: {
        type: "object",
        properties: {
          a: { type: "integer", description: "First addend." },
          b: { type: "integer", description: "Second addend." },
        },
        required: ["a", "b"],
      },
      outputSchema: {
        type: "object",
        properties: { sum: { type: "integer" } },
        required: ["sum"],
      },
      annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
    },
    {
      name: "word_count",
      title: "Word count",
      description: "Count the words in a string (defensive, read-only).",
      inputSchema: {
        type: "object",
        properties: { text: { type: "string" } },
        required: ["text"],
      },
      outputSchema: {
        type: "object",
        properties: { words: { type: "integer" } },
        required: ["words"],
      },
      annotations: { readOnlyHint: true },
    },
  ],
  resources: [
    {
      uri: "info://about",
      name: "about",
      title: "About this server",
      description: "Static description of the example server.",
      mimeType: "text/markdown",
    },
    {
      uri: "info://version",
      name: "version",
      title: "Server version",
      description: "The server's semantic version string.",
      mimeType: "text/plain",
    },
  ],
  resourceTemplates: [
    {
      uriTemplate: "greeting://{who}",
      name: "greeting",
      title: "Greeting",
      description: "A parameterized greeting resource.",
      mimeType: "text/plain",
    },
  ],
  prompts: [
    {
      name: "summarize",
      title: "Summarize text",
      description: "Ask the model to summarize the provided text.",
      arguments: [
        { name: "text", description: "The text to summarize.", required: true },
        { name: "style", description: "Optional summary style (e.g. bullet points).", required: false },
      ],
    },
    {
      name: "code_review",
      title: "Request code review",
      description: "Ask the model to review a snippet of code.",
      arguments: [{ name: "code", description: "The code to review.", required: true }],
    },
  ],
  auth: {
    scheme: "bearer",
    tokenEnvVar: "MCP_BEARER_TOKEN",
    note: "Bearer-token authorization hook — disabled by default (allow-with-TODO).",
  },
};
